export default {
  REDUCER_TYPE: {
    USERS: {
      IS_ADD_USER_BUTTON_CLICKED: 'IS_ADD_USER_BUTTON_CLICKED',
      USER_DATA: 'USER_DATA',
      SELECTED_USER_FOR_EDIT: 'SELECTED_USER_FOR_EDIT',
      USER_ACTION_MODE: 'USER_ACTION_MODE'
    }
  }
}